name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip Android project
        run: |
          mkdir buildsrc
          unzip -q Kunduz_Mines_Visitors_Android_Project_v1.1.zip -d buildsrc

      - name: Add AndroidX properties
        run: |
          cp gradle.properties buildsrc/gradle.properties

      - name:  Fix JVM target
        run: 
             sed -i 's/JavaVersion.VERSION_1_8/JavaVersion.VERSION_17/g; s/"1.8"/"17"/g' buildsrc/app/build.gradle.kts
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools platforms;android-35 build-tools;35.0.0'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build APK
        working-directory: buildsrc
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kunduz-Mines-Visitors-APK
          path: buildsrc/app/build/outputs/apk/debug/app-debug.apk
